### ISSUE TITLE
Error styling when using Twitter Bootstrap

### ISSUE THREAD

**Issue by GabrielGil** [hpneo/gmaps#44]
Hello everyone!

There is an issue that breaks all the styling in the map. The problem is in `bootstrap.css`. There is a rule not working as expected:

``` css
img {
    max-width: 100%;
    vertical-align: middle;
}
```

The solution is simple. Reject this properties to the img tag inside the map div:

``` css
#yourmap img {
    max-width: none;
    vertical-align: baseline;
}
```

Hope this can be fixed in the next version of the plugin.

Cheers
